name: clot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.2

  #route
  auto_route: ^9.3.0+1

  #network
  dio: ^5.8.0+1
  logger: ^2.5.0

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  get_it: ^7.6.7
  bloc: ^9.0.0

  #storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd/CircularStd-Book.ttf
          weight: 400