name: clot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  flutter_bloc: ^9.0.0

  #utils
  auto_route: ^9.3.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd/CircularStd-Book.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package